// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADR1Fsnc8VJIuV963P3GhL2XNkx3-8Kx4',
    appId: '1:810053569527:web:connectta-web-app',
    messagingSenderId: '810053569527',
    projectId: 'connectta-aa0a6',
    authDomain: 'connectta-aa0a6.firebaseapp.com',
    storageBucket: 'connectta-aa0a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADR1Fsnc8VJIuV963P3GhL2XNkx3-8Kx4',
    appId: '1:810053569527:android:650948f964b0f7b8003cf2',
    messagingSenderId: '810053569527',
    projectId: 'connectta-aa0a6',
    storageBucket: 'connectta-aa0a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVQRlELMy8EzzfeEnOWWxyaqUrFRnXDM',
    appId: '1:810053569527:ios:66d01fe2e5ce6e94003cf2',
    messagingSenderId: '810053569527',
    projectId: 'connectta-aa0a6',
    storageBucket: 'connectta-aa0a6.firebasestorage.app',
    iosClientId: '810053569527-118vpgoc92sl9t3bluslqosgjnlsp1vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.connecta',
  );

}